name: Terraform

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_github_token: ${{ secrets.PAT }}
      TF_VAR_repo_owner: ${{ secrets.REPO_OWNER }}
      TF_VAR_repo_name: ${{ secrets.REPO_NAME }}
      TF_VAR_deploy_public_key_path: "terraform/deploy_key.pub"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
